config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :users
  resources :games

  root "games#index"
  get "index" => "games#index"
  get "blog" => "posts#index"
  get "faq" => "pages#faq" #creates faq_path
  get "contact" => "pages#contact"
  get "recommend" => "pages#recommend"
  get "admin" => "pages#admin"

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => { :medium => "292x136>", :thumb => "100x100>" }
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/jpg', 'image/png']
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  #Sanity checking that 1 + 2 = 3
  $cake = 1
  $pie = 2
  $spy = $cake + $pie
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
    @game_price = ((((@game.reducedPrice.to_i - @game.reducedPrice.to_i * @game.sale / 100) / conversion_rate) / 100).ceil)* 100
    @price_in_doge = number_with_delimiter(((((@game.reducedPrice.to_i - @game.reducedPrice.to_i * @game.sale / 100) / conversion_rate) / 100).ceil)* 100 , :delimiter => ',')
  end

  def new
    @game = current_user.games.build
  end

  # GET /games/1/edit
  def edit
  end

  def create
    @game = current_user.games.build(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:title, :description, :reducedPrice, :sale, :user_id, :image, :stock)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def blog
  end
  def faq
  end
  def contact
  end
  def recommend
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :published, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/games/_form.html.haml
= form_for @game, html: { multipart: true } do |f|
  - if @game.errors.any?
    #error_explanation
      %h2
        = pluralize(@game.errors.count, "error")
        prohibited this game from being saved:
      %ul
        - @game.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :image
    %br/
    = f.file_field :image
  .field
    = f.label :description
    %br/
    = f.text_field :description
  .field
    = f.label :stock
    %label (Item quantity)
    %br/
    = f.number_field :stock
  .field
    / <haml:loud> f.label :reducedPrice </haml:loud>
    %label Original Price in USD
    %br/
    = f.text_field :reducedPrice
  .field
    = f.label :sale
    %label *in % off
    %br/
    = f.number_field :sale
  .actions
    = f.submit

app/views/games/edit.html.haml
- if user_signed_in?
  %h1 Editing game
  = render 'form'
  = link_to 'Show', @game
  |
  \#{link_to 'Back', games_path}
- else
  %h3 Nothing to see here!

app/views/games/index.html.haml
- conversion_rate = 0.000267033
- if user_signed_in?
  = link_to 'New Listing', new_game_path, {:class => "button success"}
  %table
    %thead
      %tr
        %th Title
        %th Stock
        %th Description
        %th Price (USD)
        %th Sale (% off)
        %th{:colspan => "3"}
    %tbody
      - @games.each do |game|
        %tr
          %td= game.title
          %td= game.stock
          %td= game.description
          %td
            $#{game.reducedPrice}
          %td
            \-#{game.sale}%
          %td= link_to 'Show', game
          %td= link_to 'Edit', edit_game_path(game)
          %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }
  %br/
.alert.button.disabled
  Because of the recent shutdown of dogeAPI, Shibe Sales is experiencing a short downtime. Purchases cannot be made at this time. We're sorry for any inconvenience this has caused.
- @games.each do |game|
  - if game.stock == nil or game.stock > 0
    .large-4.small-6.columns
      = link_to game do
        = image_tag game.image.url, :class => "style_image"
        .panel
          .inline
            %span.sale
              \-#{game.sale}%
            %span.price
              Ð
              %span#convert= number_with_delimiter(((((game.reducedPrice.to_i - game.reducedPrice.to_i * game.sale / 100) / conversion_rate) / 100).ceil)* 100 , :delimiter => ',')

app/views/games/new.html.haml
%h1 New game
= render 'form'
= link_to 'Back', games_path

app/views/games/show.html.haml
- unless (@game.stock == nil) or (@game.stock > 0)
  %h2 Nobody here but us chickens!
  %p
    The link you've clicked doesn't lead anywhere! Not sure where you wanted to go, but #{link_to "here's a link to our main page.", games_path}
- else
  - conversion_rate = 0.000267033
  %p#notice= notice
  = image_tag @game.image.url
  %p
  %h3
    %span#game-title= @game.title
  %p
    = @game.description.html_safe
  %p
    %strong Price:
    = succeed "\xC3\x90" do
      %span#reduced-price
        %span#convert= @price_in_doge
  /
    <p>
    <strong>Sale:</strong>
    <haml:loud> @game.sale </haml:loud>%
    </p>
  %fieldset
    %legend Checkout
    %form{:action => "https://www.coinpayments.net/index.php", :method => "post"}
      %input{:name => "email", :placeholder => "Your purchase will be delivered to this email", :type => "email"}/
      %input{:name => "cmd", :type => "hidden", :value => "_pay"}/
      %input{:name => "reset", :type => "hidden", :value => "1"}/
      %input{:name => "merchant", :type => "hidden", :value => "1314720bb062281182391f79c0d4d232"}/
      = hidden_field_tag 'item_name', @game.title
      %input{:name => "currency", :type => "hidden", :value => "DOGE"}/
      = hidden_field_tag 'amountf', @game_price
      %input{:name => "quantity", :type => "hidden", :value => "1"}/
      %input{:name => "allow_quantity", :type => "hidden", :value => "0"}/
      %input{:name => "want_shipping", :type => "hidden", :value => "0"}/
      %input{:name => "success_url", :type => "hidden", :value => "worked.com"}/
      %input{:name => "cancel_url", :type => "hidden", :value => "didntwork.com"}/
      %input{:name => "allow_extra", :type => "hidden", :value => "1"}/
      %button.button.success
        Purchase at #{@game.sale}% off
    %small *Your game will be delivered within 24 hours of your purchase
  - if user_signed_in?
    = link_to 'Edit', edit_game_path(@game)
    |
    \#{link_to 'Back', games_path}

app/views/layouts/application.html.haml
!!!
%html
  %body
    - conversion_rate = 0.000267033
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Shibe Sales"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
    .row
      #header.row
        .row
          .large-12.columns
            %nav.top-bar.data-topbar
              %ul.title-area
                %li.name
                  %h1
                    = link_to "Shibe Sales", root_path
              %section.top-bar-section
                %ul.right
                  %li
                    %a{href: "https://www.dogeapi.com/convert_doge"}
                      Currently operating at
                      = succeed "\u{189}/1USD" do
                        %span#header-rate= ((1 / conversion_rate) / 100).floor * 100
                  %li
                    = link_to "Announcements", blog_path
                  %li
                    = link_to "FAQ", faq_path
                  %li
                    = link_to "Contact", contact_path
                  %li
                    = link_to "Recommend", recommend_path
                  - if user_signed_in?
                    %li
                      = link_to "Account Settings", edit_user_registration_path
                    %li
                      = link_to "Log out", destroy_user_session_path, method: :delete
      - if current_page?(admin_path)
        .large-10.columns
          - flash.each do |name, msg|
            = content_tag(:div, msg, class: "alert alert-info")
          = yield
      - else
        .row
          #sidePanel
            .large-2.small-12.columns
              %img.hide-for-small{src: "https://raw.githubusercontent.com/MaxWofford/spawncamping-machine/master/app/assets/images/ShibeSales.png"}/
              %img.show-for-small{src: "https://raw.githubusercontent.com/MaxWofford/spawncamping-machine/master/app/assets/images/ShibeSalesBanner.png"}/
              .panel
                %h3
                  Miss a steam sale?
                %h5.subheader
                  Buy the game on sale with
                  = succeed "!" do
                    %a{href: "http://dogecoin.com/"} Ðogecoin
                .horizontal-line
              .hide-for-small
                .panel
                  %h6
                    Powered by:
                    %a{href: "https://www.coinpayments.net/"} CoinPayments
                  %h4
                  .horizontal-line
          .large-10.columns
            - flash.each do |name, msg|
              = content_tag(:div, msg, class: "alert alert-info")
            .head-announcement
              %p Latest announcement:
              %h2
                = link_to "/posts/#{Post.last.id}" do
                  '#{Post.last.title}'
                  %small.quiet-text by #{Post.last.author}
            = yield
      %footer#footer.row.no-border
        .large-12.columns
          .row.footer{style: "font-size: .25em;"}
            .horizontal-line
            .large-6.columns
              %p
                ©
                %a{href: ""} ShibeSales
                2014
            .large-6.columns
              %ul.inline-list.right
                - if current_page?(admin_path)
                - else
                  %li
                    = link_to "Admin Page", admin_path
                %li Build 1.0.0
        / Firebase on all pages for new features being tested on each build
        %script{src: "https://cdn.firebase.com/js/client/1.0.17/firebase.js", type: "text/javascript"}
      = javascript_include_tag "application"

app/views/pages/admin.html.haml
- if user_signed_in?
  / If the user is signed in, a sign-out link is in the header
  %h2
    Welcome, #{current_user.email}
  = link_to "Update Account", edit_user_registration_path, class: "button"
- else
  %p
    = link_to "Log in", new_user_session_path, class: "button"
    = link_to "Sign up", new_user_registration_path, class: "button"

app/views/pages/contact.html.haml
%script{src: "https://cdn.firebase.com/js/client/1.0.15/firebase.js", type: "text/javascript"}
.panel
  %h1 Want to contact us?
  %p Got questions, concerns, critiques, or feedback? We'd love to hear it! Your contact info is not required, but we'll make sure to respond if you do.
  %input#userFeedback{type: "text"}/
  %button#submit-button.success{onclick: "submit();"} Submit!
  #success-message.hide Feedback submitted successfully! We'll try to get back to you within 12 hours if you leave contact info.
:javascript
  var fb = new Firebase("https://shibe-games.firebaseio.com/feedback");
  var submit = function (userFeedback) {
    if ((document.getElementById("submit-button").className !== "success disabled") && (document.getElementById("userFeedback").value !== "")){

      var userFeedback = document.getElementById("userFeedback").value;

      //Pushes data to firebase
      fb.push({Feedback: userFeedback}); 
  
      //Disables send button after request is sent
      document.getElementById("submit-button").className += " disabled";
  
      //Reveals success message
      document.getElementById("success-message").className = document.getElementById("success-message").className.replace( /(?:^|\s)hide(?!\S)/g , '' );
      document.getElementById("success-message").className += "success alert-box";

    };
    return false;
  }

app/views/pages/faq.html.haml
.panel.quiet-text
  %h1 Frequently asked questions
  %hr/
  %h3
    Q: What is #{link_to "Dogecoin", "http://dogecoin.com/"}
  %p A: Dogecoin is a fun, new and rapidly growing form of digital currency. This form of digital currency is called "cryptocurrency"; a type of digital currency. Cryptocurrency is completely anonymous, decentralized, and extremely secure. Think of it as “Internet Currency” for the modern age
  %hr/
  %h3 Q: What is Shibe Sales?
  %p A: Shibe Sales is a Dogecoin friendly way to buy games at discount that you can’t get anywhere else!
  %hr/
  %h3 Q: When/how/where will I recieve my order?
  %p
    A: Your steam game will be gifted to you email within 24 hours of purchase.
  %hr/
  %h3 Q: How are your services?
  %p
    A: Check out #{link_to "our listing", "http://www.dogecoin.link/item/shibesales/"} on Dogecoin.link for customer reviews.
  %hr/
  %h3 Q: How do I use Dogecoin?
  %p
    A: Head on over to #{link_to "How To Doge", "http://howtodoge.com/"} to get started using Dogecoin!
  %hr/
  %h3
    Q: How was #{link_to "this site", "/"} made?
  %p
    A: With an awesome tutorial from #{link_to "One Month Rails", "https://onemonthrails.com/"}!

app/views/pages/recommend.html.haml
%script{src: "https://cdn.firebase.com/js/client/1.0.15/firebase.js", type: "text/javascript"}
:javascript
  var fb = new Firebase("https://shibe-games.firebaseio.com/recommendations/heroku");
  var recommend = function (userEmail, userFeedback) {
      var userFeedback = document.getElementById("game-title").value;
      var userEmail = document.getElementById("email").value;
   	fb.push({email: userEmail, feedback: userFeedback}); /*Pushes data to firebase*/
   	document.getElementById("instructions").innerHTML = "Recommendation recieved! You can recommend another here if you want, or head back to our main page for more awesome sales." ;
    document.getElementById("instructions").className += "success alert-box";
    document.getElementById("button").className += " disabled";
      return false;
  }
.panel
  %h1 Want us to stock up on a game when it goes on sale? Recommend it here!
  %h4#instructions We'll also send you a notification if you provide your email.
  %form
    %input#game-title{placeholder: "Game title", type: "text"}/
    %input#email{placeholder: "Email (option)", type: "email"}/
  %button.success#button{onclick: "recommend();"} Recommend

app/views/posts/_form.html.haml
= form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :content
    %br/
    = f.text_area :content
  .field
    = f.label :published
    %br/
    = f.date_select :published
  .field
    = f.label :author
    %br/
    = f.text_field :author
  .actions
    = f.submit

app/views/posts/edit.html.haml
- if user_signed_in?
  %h1 Editing post
  = render 'form'
  = link_to 'Show', @post
  |
  \#{link_to 'Back', posts_path}
- else
  %h3 Nothing to see here!

app/views/posts/index.html.haml
- if user_signed_in?
  = link_to 'New Post', new_post_path, {:class => "success button"}
- @posts.each do |post|
  .row
    .large-10.small-12.columns.panel
      %h3= post.title
      %small= post.author
      %small= post.published
      .horizontal-line
      %br/
      %p= post.content.html_safe
      - if user_signed_in?
        %p= "#{link_to 'Show', post} | #{link_to 'Edit', edit_post_path(post)} | #{link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }}".html_safe
%br/

app/views/posts/new.html.haml
%h1 New post
= render 'form'
= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice
- if user_signed_in?
  %p
    %strong Title:
    = @post.title
  %p
    %strong Content:
    = @post.content.html_safe
  %p
    %strong Published:
    = @post.published
  %p
    %strong Author:
    = @post.author
  = link_to 'Edit', edit_post_path(@post)
  |
  \#{link_to 'Back', posts_path}
- else
  .row
    .large-10.small-12.columns.panel
      %h3= @post.title
      %small
        = @post.author
        = @post.published
      .horizontal-line
      %br/
      %p= @post.content.html_safe